package com.amazonaws.lambda.demo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "archivos")
@Getter
@NoArgsConstructor
@Setter
@ToString
public class Archivo {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "id_archivo")
    private String id;

    @JsonProperty("nombre_archivo")
    @DynamoDBAttribute(attributeName = "nombre_archivo")
    private String nombreArchivo;
    
    @JsonProperty("fechaRegistro")
    @DynamoDBAttribute(attributeName = "fecha_registro")
    private String fechaRegistro;

    @JsonProperty("esta_cargado")
    @DynamoDBAttribute(attributeName = "esta_cargado")
    private Boolean estaCargado;
}
